obs:
  host: 192.168.8.187
  port: 4455
  password: YAzsQeJ1OPMkABG6

app_scene_mappings:
  Emacs: editor-focused
  Alacritty: terminal-f
  Google Chrome: browser-focused

polling_interval: 0.5
log_level: INFO
log_file: ~/.config/vibeobs/vibeobs.log
